version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: kchef
      MYSQL_USER: chef
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306