// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using edk.Kchef.Infrastructure.Data.EF.Context;

#nullable disable

namespace edk.Kchef.Infrastructure.Data.Migrations
{
    [DbContext(typeof(KChefContext))]
    [Migration("20230107143943_CreateTableProductPrices")]
    partial class CreateTableProductPrices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("edk.Kchef.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("AmountMax")
                        .HasColumnType("float");

                    b.Property<float>("AmountMin")
                        .HasColumnType("float");

                    b.Property<float>("Balance")
                        .HasColumnType("float");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Unity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PKey_ProductId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("edk.Kchef.Domain.Products.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrice");
                });

            modelBuilder.Entity("edk.Kchef.Domain.Products.ProductPrice", b =>
                {
                    b.HasOne("edk.Kchef.Domain.Products.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("edk.Kchef.Domain.Products.Product", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
